-- Create pharmacies table
CREATE TABLE IF NOT EXISTS pharmacies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  cell_phone VARCHAR(50),
  address TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index on created_at for sorting
CREATE INDEX IF NOT EXISTS idx_pharmacies_created_at ON pharmacies(created_at DESC);

-- Create index on name for search
CREATE INDEX IF NOT EXISTS idx_pharmacies_name ON pharmacies(name);

-- Enable RLS (Row Level Security)
ALTER TABLE pharmacies ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Enable read access for all users" ON pharmacies
  FOR SELECT USING (true);

-- Create policy for insert access (for authenticated users)
CREATE POLICY "Enable insert for authenticated users" ON pharmacies
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Create policy for update access (for authenticated users)
CREATE POLICY "Enable update for authenticated users" ON pharmacies
  FOR UPDATE USING (auth.role() = 'authenticated');

-- Create policy for delete access (for authenticated users)
CREATE POLICY "Enable delete for authenticated users" ON pharmacies
  FOR DELETE USING (auth.role() = 'authenticated');

-- Add comments for documentation
COMMENT ON TABLE pharmacies IS 'Tabla para almacenar farmacias de turno';
COMMENT ON COLUMN pharmacies.id IS 'Identificador único autoincremental';
COMMENT ON COLUMN pharmacies.name IS 'Nombre de la farmacia';
COMMENT ON COLUMN pharmacies.phone IS 'Número de teléfono principal';
COMMENT ON COLUMN pharmacies.cell_phone IS 'Número de teléfono celular (opcional)';
COMMENT ON COLUMN pharmacies.address IS 'Dirección completa de la farmacia';
COMMENT ON COLUMN pharmacies.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN pharmacies.updated_at IS 'Fecha de última actualización del registro';

-- Create trigger for updated_at
CREATE TRIGGER update_pharmacies_updated_at 
    BEFORE UPDATE ON pharmacies 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();
