-- Create obituaries table
CREATE TABLE IF NOT EXISTS obituaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  age INTEGER NOT NULL,
  service_info TEXT NOT NULL,
  date TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index on date for better performance
CREATE INDEX IF NOT EXISTS idx_obituaries_date ON obituaries(date DESC);

-- Create index on created_at for sorting
CREATE INDEX IF NOT EXISTS idx_obituaries_created_at ON obituaries(created_at DESC);

-- Enable RLS (Row Level Security)
ALTER TABLE obituaries ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Enable read access for all users" ON obituaries
  FOR SELECT USING (true);

-- Create policy for insert access (for authenticated users)
CREATE POLICY "Enable insert for authenticated users" ON obituaries
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Create policy for update access (for authenticated users)
CREATE POLICY "Enable update for authenticated users" ON obituaries
  FOR UPDATE USING (auth.role() = 'authenticated');

-- Create policy for delete access (for authenticated users)
CREATE POLICY "Enable delete for authenticated users" ON obituaries
  FOR DELETE USING (auth.role() = 'authenticated');

-- Add comments for documentation
COMMENT ON TABLE obituaries IS 'Tabla para almacenar necrológicas y avisos fúnebres';
COMMENT ON COLUMN obituaries.id IS 'Identificador único autoincremental';
COMMENT ON COLUMN obituaries.full_name IS 'Nombre completo del fallecido';
COMMENT ON COLUMN obituaries.age IS 'Edad del fallecido';
COMMENT ON COLUMN obituaries.service_info IS 'Información del servicio fúnebre (lugar, dirección, hora)';
COMMENT ON COLUMN obituaries.date IS 'Fecha del servicio o fallecimiento';
COMMENT ON COLUMN obituaries.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN obituaries.updated_at IS 'Fecha de última actualización del registro';

-- Create trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_obituaries_updated_at 
    BEFORE UPDATE ON obituaries 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();
