-- Update existing obituaries table
-- This script modifies the existing table to match our requirements

-- Check if table exists and add missing columns if needed
DO $$
BEGIN
    -- Add missing columns if they don't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'obituaries' AND column_name = 'id') THEN
        ALTER TABLE obituaries ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'obituaries' AND column_name = 'full_name') THEN
        ALTER TABLE obituaries ADD COLUMN full_name VARCHAR(255) NOT NULL DEFAULT '';
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'obituaries' AND column_name = 'age') THEN
        ALTER TABLE obituaries ADD COLUMN age INTEGER NOT NULL DEFAULT 0;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'obituaries' AND column_name = 'service_info') THEN
        ALTER TABLE obituaries ADD COLUMN service_info TEXT NOT NULL DEFAULT '';
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'obituaries' AND column_name = 'date') THEN
        ALTER TABLE obituaries ADD COLUMN date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'obituaries' AND column_name = 'created_at') THEN
        ALTER TABLE obituaries ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'obituaries' AND column_name = 'updated_at') THEN
        ALTER TABLE obituaries ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
    END IF;
END $$;

-- Create indexes if they don't exist
CREATE INDEX IF NOT EXISTS idx_obituaries_date ON obituaries(date DESC);
CREATE INDEX IF NOT EXISTS idx_obituaries_created_at ON obituaries(created_at DESC);

-- Enable RLS if not enabled
ALTER TABLE obituaries ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (to avoid conflicts)
DROP POLICY IF EXISTS "Enable read access for all users" ON obituaries;
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON obituaries;
DROP POLICY IF EXISTS "Enable update for authenticated users" ON obituaries;
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON obituaries;

-- Create new policies
CREATE POLICY "Enable read access for all users" ON obituaries
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON obituaries
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users" ON obituaries
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Enable delete for authenticated users" ON obituaries
  FOR DELETE USING (auth.role() = 'authenticated');

-- Add comments if they don't exist
COMMENT ON TABLE obituaries IS 'Tabla para almacenar necrológicas y avisos fúnebres';
COMMENT ON COLUMN obituaries.id IS 'Identificador único autoincremental';
COMMENT ON COLUMN obituaries.full_name IS 'Nombre completo del fallecido';
COMMENT ON COLUMN obituaries.age IS 'Edad del fallecido';
COMMENT ON COLUMN obituaries.service_info IS 'Información del servicio fúnebre (lugar, dirección, hora)';
COMMENT ON COLUMN obituaries.date IS 'Fecha del servicio o fallecimiento';
COMMENT ON COLUMN obituaries.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN obituaries.updated_at IS 'Fecha de última actualización del registro';

-- Create trigger function if it doesn't exist
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Drop existing trigger if it exists
DROP TRIGGER IF EXISTS update_obituaries_updated_at ON obituaries;

-- Create trigger
CREATE TRIGGER update_obituaries_updated_at 
    BEFORE UPDATE ON obituaries 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();
